### ISSUE TITLE
Add Label to items

### ISSUE THREAD

**Issue by albertovm** [levey/AwesomeMenu#38]
I am trying to fade some labels to each menu item.
Each label should appear when I touch addButton to open menu items, and disappear when closed or selected.

It works with:

(void)AwesomeMenuDidFinishAnimationClose:(AwesomeMenu *)menu
{
[UIView beginAnimations:nil context:NULL];
[UIView setAnimationDelay:0.0];
[UIView setAnimationDuration:1.0];
[label setAlpha:0];
[UIView commitAnimations];
NSLog(@"Menu was closed!");
}

(void)AwesomeMenuDidFinishAnimationOpen:(AwesomeMenu *)menu
{
[UIView beginAnimations:nil context:NULL];
[UIView setAnimationDelay:0.0];
[UIView setAnimationDuration:1.0];
[label setAlpha:1];
[UIView commitAnimations];
NSLog(@"Menu is open!");
}

But is there how to startup my label fade in/out WITH (same time) menu animation?
It starts only when last menu animation item finish to move.

Thanx!

**Comment by levey** [comment]
You can customize AwesomeMenuItem
