### ISSUE TITLE
Init method changed

### ISSUE THREAD

**Issue by mihaifischeratdensio** [levey/AwesomeMenu#56]
I just got AwesomeMenu via CocoaPods, and the - (id)initWithFrame:(CGRect)frame startItem:(AwesomeMenuItem*)startItem optionMenus:(NSArray *)aMenusArray;  was changed to - (id)initWithFrame:(CGRect)frame menus:(NSArray *)aMenusArray;
why can't we customise the start button anymore?

**Comment by levey** [comment]
Hi the latest init method should be `-initWithFrame:startItem:menuItems:`
Already expose start button.
